# .github/workflows/docker-build-push.yml

name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: docker.io
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/dagster-beta-usercode

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=long
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

# How to use:
# 1. Go to your GitHub repository settings
# 2. Navigate to Secrets and Variables > Actions
# 3. Add these secrets:
#    - DOCKERHUB_USERNAME: Your DockerHub username
#    - DOCKERHUB_TOKEN: Your DockerHub access token (not your password)
#
# Tag formats that will be created:
# - For branches: your-username/my-dagster-project:branch-name
# - For PRs: your-username/my-dagster-project:pr-number
# - For tags: your-username/my-dagster-project:1.0.0
# - For main branch: your-username/my-dagster-project:latest
# - For commits: your-username/my-dagster-project:sha-xxxxx