name: Build and Push Dagster Docker Image

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag (e.g., v1.0.0)'
        required: true
        default: 'latest'
  push:
    branches: [ main ]
    tags: [ 'v*' ]
    paths:
      - 'hts_dagster_sample/**'
      - 'Dockerfile'
      - 'pyproject.toml'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 4: Set image tag
      - name: Set image tag
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "IMAGE_TAG=${{ github.event.inputs.image_tag }}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          fi

      # Step 5: Display build info
      - name: Display build information
        run: |
          echo "Building image with tag: $IMAGE_TAG"
          echo "Context directory: ."
          echo "Dockerfile path: ./Dockerfile"

      # Step 6: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/dagster-beta-usercode:${{ env.IMAGE_TAG }}
            ${{ secrets.DOCKER_USERNAME }}/dagster-beta-usercode:latest

      # Step 7: Update Kubernetes deployment (if needed)
      - name: Update Kubernetes deployment
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "New image has been pushed: ${{ secrets.DOCKER_USERNAME }}/dagster-usercode:${{ env.IMAGE_TAG }}"
          echo "To update your Dagster deployment, run:"
          echo "kubectl patch userdeployment my-dagster-project --type=json -p='[{\"op\": \"replace\", \"path\": \"/spec/deployment/image/tag\", \"value\": \"${{ env.IMAGE_TAG }}\"}]'"

      # Step 8: Image digest
      - name: Image digest
        run: echo ${{ steps.build.outputs.digest }}